### ISSUE TITLE
Deprecated Subnet_id 

### ISSUE THREAD

**Issue by Ochir** [sport24ru/terraform-yandex-managed-kubernetes#2]
During creation of K8s cluster the following warning appears.

_Warning: "allocation_policy.0.location.0.subnet_id": [DEPRECATED] The 'subnet_id' field has been deprecated. Please use 'subnet_ids under network_interface' instead._

Yandex.Cloud CLI 0.79.0

**Comment by alxrem** [comment]
Fixed in release 2.1.0

Thank you for reporting.
