### ISSUE TITLE
Deprecated nodeTemplate.v4AddressSpec

### ISSUE THREAD

**Issue by Alexdrr** [sport24ru/terraform-yandex-managed-kubernetes#3]
Hi, node group creation error when enabled _nat  = true_
`_node_template.v4_address_spec: can't use "node_template.v4_address_spec" together with "node_template.network_interface_specs"_`
The problem was solved by deleting the line [155](https://github.com/sport24ru/terraform-yandex-managed-kubernetes/blob/master/main.tf#L155)

**Comment by alxrem** [comment]
Fixed by release 2.2.0
